version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=nombre-de-tu-base-de-datos
      - DB_USERNAME=nombre-de-usuario
      - DB_PASSWORD=contraseña

  db:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=nombre-de-tu-base-de-datos
      - POSTGRES_USER=nombre-de-usuario
      - POSTGRES_PASSWORD=contraseña
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
